// =============================================================================
// Revolute joint clearance OpenVDB field-contact dynamics trial.
//
// Body1 is fixed. Body2 and Body3 are integrated as one compound rigid body.
// Contact is generated by querying the Body3 pin surface against the fixed Body1
// bore sparse-SDF, matching the RecurDyn model topology:
//
//   Ground -- Fixed1 -- Body1
//   Body2  -- Fixed2 -- Body3
//   Body3.Cylinder1 <-> Body1.Subtract1 GeoSurContact1
//
// =============================================================================

#define _USE_MATH_DEFINES

#include <algorithm>
#include <chrono>
#include <cmath>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

#include "chrono/collision/ChFieldContactRuntime.h"

#include <openvdb/openvdb.h>
#include <openvdb/tools/Interpolation.h>
#include <openvdb/tools/MeshToVolume.h>

using namespace chrono;
using namespace chrono::fieldcontact;

namespace {

struct Mat3 {
    double m[3][3] = {{1, 0, 0}, {0, 1, 0}, {0, 0, 1}};

    ChVector3d operator*(const ChVector3d& v) const {
        return ChVector3d(m[0][0] * v.x() + m[0][1] * v.y() + m[0][2] * v.z(),
                          m[1][0] * v.x() + m[1][1] * v.y() + m[1][2] * v.z(),
                          m[2][0] * v.x() + m[2][1] * v.y() + m[2][2] * v.z());
    }
};

struct Quat {
    double w = 1.0;
    double x = 0.0;
    double y = 0.0;
    double z = 0.0;
};

struct Mesh {
    std::vector<ChVector3d> vertices;
    std::vector<TriangleFace> faces;
};

struct SparseSDF {
    openvdb::FloatGrid::Ptr grid;
    double voxel_size = 2.0e-3;
};

struct ReferenceRow {
    double time = 0.0;
    ChVector3d pos = ChVector3d(0, 0, 0);
    ChVector3d vel = ChVector3d(0, 0, 0);
    ChVector3d acc = ChVector3d(0, 0, 0);
};

struct ContactSettings {
    double bpen = 1.0e-5;
    double max_pen = 3.0e-2;
    int korder = 2;
    double pressure_at_bpen = 5.0e-2;
    double damping_pressure = 1.0e2;
};

struct ContactResult {
    ChVector3d force = ChVector3d(0, 0, 0);
    ChVector3d torque = ChVector3d(0, 0, 0);
    double min_phi = std::numeric_limits<double>::max();
    double max_effective_penetration = 0.0;
    int active_samples = 0;
    int patch_count = 0;
};

struct RigidState {
    ChVector3d pos = ChVector3d(0, 0, 0);        // compound COM in world frame
    Quat rot;                                    // body to world
    ChVector3d vel = ChVector3d(0, 0, 0);        // compound COM velocity, world
    ChVector3d omega_body = ChVector3d(0, 0, 0); // angular velocity in compound body frame
};

struct BodyKinematics {
    ChVector3d pos = ChVector3d(0, 0, 0);
    ChVector3d vel = ChVector3d(0, 0, 0);
    ChVector3d acc = ChVector3d(0, 0, 0);
};

using SdfSampler = openvdb::tools::GridSampler<openvdb::FloatGrid::TreeType, openvdb::tools::BoxSampler>;

static std::string GetProjectRoot() {
    auto path = std::filesystem::current_path();
    for (int i = 0; i < 8; i++) {
        if (std::filesystem::exists(path / "src") && std::filesystem::exists(path / "assets")) {
            return path.string();
        }
        if (!path.has_parent_path() || path == path.parent_path()) {
            break;
        }
        path = path.parent_path();
    }
    return std::filesystem::current_path().string();
}

static Mat3 Transpose(const Mat3& a) {
    Mat3 out;
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            out.m[i][j] = a.m[j][i];
        }
    }
    return out;
}

static Mat3 Add(const Mat3& a, const Mat3& b) {
    Mat3 out;
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            out.m[i][j] = a.m[i][j] + b.m[i][j];
        }
    }
    return out;
}

static Mat3 Scale(const Mat3& a, double scale) {
    Mat3 out;
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            out.m[i][j] = scale * a.m[i][j];
        }
    }
    return out;
}

static Mat3 ParallelAxis(double mass, const ChVector3d& r) {
    Mat3 out;
    const double r2 = r.Dot(r);
    out.m[0][0] = mass * (r2 - r.x() * r.x());
    out.m[1][1] = mass * (r2 - r.y() * r.y());
    out.m[2][2] = mass * (r2 - r.z() * r.z());
    out.m[0][1] = out.m[1][0] = -mass * r.x() * r.y();
    out.m[0][2] = out.m[2][0] = -mass * r.x() * r.z();
    out.m[1][2] = out.m[2][1] = -mass * r.y() * r.z();
    return out;
}

static Mat3 Inverse(const Mat3& a) {
    const double det = a.m[0][0] * (a.m[1][1] * a.m[2][2] - a.m[1][2] * a.m[2][1]) -
                       a.m[0][1] * (a.m[1][0] * a.m[2][2] - a.m[1][2] * a.m[2][0]) +
                       a.m[0][2] * (a.m[1][0] * a.m[2][1] - a.m[1][1] * a.m[2][0]);
    if (std::abs(det) < 1.0e-18) {
        throw std::runtime_error("Singular inertia matrix");
    }
    const double inv_det = 1.0 / det;
    Mat3 out;
    out.m[0][0] = (a.m[1][1] * a.m[2][2] - a.m[1][2] * a.m[2][1]) * inv_det;
    out.m[0][1] = (a.m[0][2] * a.m[2][1] - a.m[0][1] * a.m[2][2]) * inv_det;
    out.m[0][2] = (a.m[0][1] * a.m[1][2] - a.m[0][2] * a.m[1][1]) * inv_det;
    out.m[1][0] = (a.m[1][2] * a.m[2][0] - a.m[1][0] * a.m[2][2]) * inv_det;
    out.m[1][1] = (a.m[0][0] * a.m[2][2] - a.m[0][2] * a.m[2][0]) * inv_det;
    out.m[1][2] = (a.m[0][2] * a.m[1][0] - a.m[0][0] * a.m[1][2]) * inv_det;
    out.m[2][0] = (a.m[1][0] * a.m[2][1] - a.m[1][1] * a.m[2][0]) * inv_det;
    out.m[2][1] = (a.m[0][1] * a.m[2][0] - a.m[0][0] * a.m[2][1]) * inv_det;
    out.m[2][2] = (a.m[0][0] * a.m[1][1] - a.m[0][1] * a.m[1][0]) * inv_det;
    return out;
}

static Quat Multiply(const Quat& a, const Quat& b) {
    return Quat{a.w * b.w - a.x * b.x - a.y * b.y - a.z * b.z,
                a.w * b.x + a.x * b.w + a.y * b.z - a.z * b.y,
                a.w * b.y - a.x * b.z + a.y * b.w + a.z * b.x,
                a.w * b.z + a.x * b.y - a.y * b.x + a.z * b.w};
}

static void Normalize(Quat& q) {
    const double n = std::sqrt(q.w * q.w + q.x * q.x + q.y * q.y + q.z * q.z);
    if (n <= 0.0) {
        q = Quat{};
        return;
    }
    q.w /= n;
    q.x /= n;
    q.y /= n;
    q.z /= n;
}

static Mat3 ToMat3(const Quat& q_in) {
    Quat q = q_in;
    Normalize(q);
    Mat3 out;
    const double ww = q.w * q.w;
    const double xx = q.x * q.x;
    const double yy = q.y * q.y;
    const double zz = q.z * q.z;
    out.m[0][0] = ww + xx - yy - zz;
    out.m[1][1] = ww - xx + yy - zz;
    out.m[2][2] = ww - xx - yy + zz;
    out.m[0][1] = 2.0 * (q.x * q.y - q.w * q.z);
    out.m[1][0] = 2.0 * (q.x * q.y + q.w * q.z);
    out.m[0][2] = 2.0 * (q.x * q.z + q.w * q.y);
    out.m[2][0] = 2.0 * (q.x * q.z - q.w * q.y);
    out.m[1][2] = 2.0 * (q.y * q.z - q.w * q.x);
    out.m[2][1] = 2.0 * (q.y * q.z + q.w * q.x);
    return out;
}

static Mesh LoadObj(const std::filesystem::path& path) {
    Mesh mesh;
    std::ifstream in(path);
    if (!in) {
        throw std::runtime_error("Cannot open OBJ: " + path.string());
    }

    std::string line;
    while (std::getline(in, line)) {
        std::istringstream iss(line);
        std::string tag;
        iss >> tag;
        if (tag == "v") {
            double x = 0.0;
            double y = 0.0;
            double z = 0.0;
            iss >> x >> y >> z;
            mesh.vertices.emplace_back(x, y, z);
        } else if (tag == "f") {
            std::vector<int> ids;
            std::string token;
            while (iss >> token) {
                size_t slash = token.find('/');
                std::string v = slash == std::string::npos ? token : token.substr(0, slash);
                int idx = std::stoi(v);
                if (idx < 0) {
                    idx = static_cast<int>(mesh.vertices.size()) + idx + 1;
                }
                ids.push_back(idx - 1);
            }
            for (size_t i = 1; i + 1 < ids.size(); i++) {
                mesh.faces.push_back(TriangleFace{ids[0], ids[i], ids[i + 1]});
            }
        }
    }
    return mesh;
}

static SparseSDF BuildSDF(const Mesh& mesh, double voxel_size, float half_width_voxels) {
    std::vector<openvdb::Vec3s> points;
    std::vector<openvdb::Vec3I> triangles;
    points.reserve(mesh.vertices.size());
    triangles.reserve(mesh.faces.size());
    for (const auto& v : mesh.vertices) {
        points.emplace_back(static_cast<float>(v.x()), static_cast<float>(v.y()), static_cast<float>(v.z()));
    }
    for (const auto& face : mesh.faces) {
        triangles.emplace_back(face.v0, face.v1, face.v2);
    }
    auto transform = openvdb::math::Transform::createLinearTransform(voxel_size);
    auto grid = openvdb::tools::meshToLevelSet<openvdb::FloatGrid>(*transform, points, triangles, half_width_voxels);
    grid->setGridClass(openvdb::GRID_LEVEL_SET);
    return SparseSDF{grid, voxel_size};
}

static double SampleSDF(SdfSampler& sampler, const ChVector3d& p) {
    return static_cast<double>(sampler.wsSample(openvdb::Vec3d(p.x(), p.y(), p.z())));
}

static ChVector3d SDFGradient(const SparseSDF& sdf, SdfSampler& sampler, const ChVector3d& p) {
    const double h = 0.5 * sdf.voxel_size;
    ChVector3d grad((SampleSDF(sampler, p + ChVector3d(h, 0, 0)) -
                         SampleSDF(sampler, p - ChVector3d(h, 0, 0))) /
                        (2.0 * h),
                    (SampleSDF(sampler, p + ChVector3d(0, h, 0)) -
                         SampleSDF(sampler, p - ChVector3d(0, h, 0))) /
                        (2.0 * h),
                    (SampleSDF(sampler, p + ChVector3d(0, 0, h)) -
                         SampleSDF(sampler, p - ChVector3d(0, 0, h))) /
                        (2.0 * h));
    return SafeNormalize(grad, ChVector3d(0, 1, 0));
}

static std::vector<std::string> SplitCsvLine(const std::string& line) {
    std::vector<std::string> out;
    std::string token;
    std::istringstream stream(line);
    while (std::getline(stream, token, ',')) {
        out.push_back(token);
    }
    return out;
}

static std::vector<ReferenceRow> LoadReference(const std::filesystem::path& path) {
    std::ifstream in(path);
    if (!in) {
        throw std::runtime_error("Cannot open reference CSV: " + path.string());
    }
    std::string line;
    std::getline(in, line);
    std::vector<ReferenceRow> rows;
    while (std::getline(in, line)) {
        if (line.empty()) {
            continue;
        }
        auto cols = SplitCsvLine(line);
        if (cols.size() < 18) {
            continue;
        }
        ReferenceRow row;
        row.time = std::stod(cols[0]);
        row.pos = ChVector3d(std::stod(cols[9]), std::stod(cols[10]), std::stod(cols[11]));
        row.vel = ChVector3d(std::stod(cols[12]), std::stod(cols[13]), std::stod(cols[14]));
        row.acc = ChVector3d(std::stod(cols[15]), std::stod(cols[16]), std::stod(cols[17]));
        rows.push_back(row);
    }
    return rows;
}

static double Pressure(double effective_penetration, double normal_velocity, const ContactSettings& settings) {
    if (effective_penetration <= 0.0) {
        return 0.0;
    }
    const double x = std::min(effective_penetration, settings.max_pen) / settings.bpen;
    const double elastic = settings.pressure_at_bpen * std::pow(x, static_cast<double>(settings.korder));
    const double damping = settings.damping_pressure * x * std::max(-normal_velocity, 0.0);
    return elastic + damping;
}

static ContactResult EvaluateContact(const SurfaceGraph& pin_graph,
                                     const SparseSDF& bore_sdf,
                                     const RigidState& state,
                                     const ContactSettings& settings) {
    ContactResult result;
    std::vector<int> active_indices;
    active_indices.reserve(pin_graph.samples.size());
    SdfSampler sampler(bore_sdf.grid->tree(), bore_sdf.grid->transform());
    const Mat3 rmat = ToMat3(state.rot);
    const ChVector3d omega_world = rmat * state.omega_body;

    for (const auto& sample : pin_graph.samples) {
        ChVector3d r_world = rmat * sample.local_pos;
        ChVector3d world_pos = state.pos + r_world;
        const double phi = SampleSDF(sampler, world_pos);
        result.min_phi = std::min(result.min_phi, phi);
        const double effective_penetration = std::min(std::max(settings.bpen - phi, 0.0), settings.max_pen);
        if (effective_penetration <= 0.0 || sample.area <= 0.0) {
            continue;
        }

        ChVector3d normal = SDFGradient(bore_sdf, sampler, world_pos);
        ChVector3d point_velocity = state.vel + omega_world.Cross(r_world);
        const double normal_velocity = point_velocity.Dot(normal);
        const double force_mag = Pressure(effective_penetration, normal_velocity, settings) * sample.area;
        ChVector3d force = normal * force_mag;
        result.force += force;
        result.torque += r_world.Cross(force);
        result.max_effective_penetration = std::max(result.max_effective_penetration, effective_penetration);
        result.active_samples++;
        active_indices.push_back(sample.id);
    }

    result.patch_count = static_cast<int>(pin_graph.FindConnectedComponents(active_indices).size());
    return result;
}

static BodyKinematics KinematicsAt(const RigidState& state,
                                   const ChVector3d& local_offset_from_compound_com,
                                   const ChVector3d& acc_com,
                                   const ChVector3d& alpha_body) {
    const Mat3 rmat = ToMat3(state.rot);
    const ChVector3d r_world = rmat * local_offset_from_compound_com;
    const ChVector3d omega_world = rmat * state.omega_body;
    const ChVector3d alpha_world = rmat * alpha_body;
    BodyKinematics out;
    out.pos = state.pos + r_world;
    out.vel = state.vel + omega_world.Cross(r_world);
    out.acc = acc_com + alpha_world.Cross(r_world) + omega_world.Cross(omega_world.Cross(r_world));
    return out;
}

static double Rms(const std::vector<double>& values) {
    if (values.empty()) {
        return 0.0;
    }
    double sum = 0.0;
    for (double v : values) {
        sum += v * v;
    }
    return std::sqrt(sum / static_cast<double>(values.size()));
}

static double MaxAbs(const std::vector<double>& values) {
    double out = 0.0;
    for (double v : values) {
        out = std::max(out, std::abs(v));
    }
    return out;
}

static void AddComponentErrors(const ChVector3d& value, const ChVector3d& ref, std::vector<double>& ex,
                               std::vector<double>& ey, std::vector<double>& ez) {
    ex.push_back(value.x() - ref.x());
    ey.push_back(value.y() - ref.y());
    ez.push_back(value.z() - ref.z());
}

}  // namespace

int main(int argc, char** argv) {
    try {
        using Clock = std::chrono::steady_clock;
        const auto wall_start = Clock::now();
        openvdb::initialize();
        const std::string root = GetProjectRoot();
        const auto asset_dir = std::filesystem::path(root) / "assets" / "rev_joint_clearance";
        std::string out_name = "rev_joint_clearance_openvdb";
        double duration_limit = std::numeric_limits<double>::quiet_NaN();
        double dt = 2.0e-5;
        double pressure_at_bpen = 5.0e-2;
        double damping_pressure = 1.0e2;
        double voxel_size = 2.0e-3;

        auto parse_arg_value = [](const std::string& arg, const std::string& key) -> std::string {
            const std::string prefix = key + "=";
            if (arg.rfind(prefix, 0) == 0) {
                return arg.substr(prefix.size());
            }
            return "";
        };

        for (int i = 1; i < argc; i++) {
            std::string arg = argv[i];
            std::string value = parse_arg_value(arg, "--out-name");
            if (!value.empty()) {
                out_name = value;
                continue;
            }
            value = parse_arg_value(arg, "--duration");
            if (!value.empty()) {
                duration_limit = std::stod(value);
                continue;
            }
            value = parse_arg_value(arg, "--dt");
            if (!value.empty()) {
                dt = std::stod(value);
                continue;
            }
            value = parse_arg_value(arg, "--pressure-at-bpen");
            if (!value.empty()) {
                pressure_at_bpen = std::stod(value);
                continue;
            }
            value = parse_arg_value(arg, "--damping-pressure");
            if (!value.empty()) {
                damping_pressure = std::stod(value);
                continue;
            }
            value = parse_arg_value(arg, "--voxel-size");
            if (!value.empty()) {
                voxel_size = std::stod(value);
            }
        }

        const auto out_dir = std::filesystem::path(root) / "out" / out_name;
        std::filesystem::create_directories(out_dir);

        Mesh bore_mesh = LoadObj(asset_dir / "models" / "body1_subtract1_centered.obj");
        Mesh pin_mesh_body3 = LoadObj(asset_dir / "models" / "body3_cylinder1_centered.obj");

        const double m2 = 271.0;
        const double m3 = 12984.280977103;
        const double mass = m2 + m3;
        const ChVector3d body2_cm_local(1.64388630568497e-06, 8.35588256883334e-05, 2.65983598394373);
        const ChVector3d body3_cm_local(0.0, 0.0, 0.0);
        const ChVector3d compound_cm_local = (body2_cm_local * m2 + body3_cm_local * m3) / mass;
        const ChVector3d r2_local = body2_cm_local - compound_cm_local;
        const ChVector3d r3_local = body3_cm_local - compound_cm_local;

        Mat3 i2_cm;
        i2_cm.m[0][0] = 202.0;
        i2_cm.m[1][1] = 359.0;
        i2_cm.m[2][2] = 203.0;
        i2_cm.m[0][1] = i2_cm.m[1][0] = 0.244945783962547;
        i2_cm.m[0][2] = i2_cm.m[2][0] = -0.0295154838928402;
        i2_cm.m[1][2] = i2_cm.m[2][1] = -1.39749450062735;

        Mat3 i3_cm;
        i3_cm.m[0][0] = 1314.65844893167;
        i3_cm.m[1][1] = 7971.80750823384;
        i3_cm.m[2][2] = 7971.80750823384;
        i3_cm.m[0][2] = i3_cm.m[2][0] = 3.02128692434659e-13;

        const Mat3 inertia_body = Add(Add(i2_cm, ParallelAxis(m2, r2_local)), Add(i3_cm, ParallelAxis(m3, r3_local)));
        const Mat3 inertia_inv_body = Inverse(inertia_body);

        for (auto& vertex : pin_mesh_body3.vertices) {
            vertex += r3_local;
        }

        SparseSDF bore_sdf = BuildSDF(bore_mesh, voxel_size, 32.0f);
        SurfaceGraph pin_graph = MakeTriangleMeshSurfaceGraph(pin_mesh_body3.vertices, pin_mesh_body3.faces);
        auto body2_ref = LoadReference(asset_dir / "data" / "body2.csv");
        auto body3_ref = LoadReference(asset_dir / "data" / "body3.csv");
        if (body2_ref.empty() || body3_ref.empty() || body2_ref.size() != body3_ref.size()) {
            throw std::runtime_error("Invalid rev_joint_clearance reference CSV data");
        }

        ContactSettings contact;
        contact.pressure_at_bpen = pressure_at_bpen;
        contact.damping_pressure = damping_pressure;

        RigidState state;
        state.pos = compound_cm_local;

        const double run_until = std::isnan(duration_limit) ? body2_ref.back().time
                                                            : std::min(duration_limit, body2_ref.back().time);

        std::ofstream frames(out_dir / "rev_joint_clearance_frames.csv");
        frames << std::setprecision(16);
        frames << "time,body2_x,body2_y,body2_z,ref_body2_x,ref_body2_y,ref_body2_z,"
                  "body3_x,body3_y,body3_z,ref_body3_x,ref_body3_y,ref_body3_z,"
                  "body2_vx,body2_vy,body2_vz,ref_body2_vx,ref_body2_vy,ref_body2_vz,"
                  "body3_vx,body3_vy,body3_vz,ref_body3_vx,ref_body3_vy,ref_body3_vz,"
                  "patch_count,active_samples,min_phi,max_effective_penetration,force_x,force_y,force_z,"
                  "torque_x,torque_y,torque_z\n";

        std::vector<double> b2_x_err, b2_y_err, b2_z_err;
        std::vector<double> b3_x_err, b3_y_err, b3_z_err;
        std::vector<double> b2_y_err_after, b2_z_err_after, b3_y_err_after, b3_z_err_after;
        double time = 0.0;
        double first_contact_time = std::numeric_limits<double>::quiet_NaN();
        double max_body3_xy_radius = 0.0;
        double max_effective_penetration_seen = 0.0;
        int max_patch_count = 0;
        ContactResult last_contact;
        ChVector3d last_acc_com(0, -9.80665, 0);
        ChVector3d last_alpha_body(0, 0, 0);

        const auto integration_start = Clock::now();
        for (size_t i = 0; i < body2_ref.size(); i++) {
            const auto& ref2 = body2_ref[i];
            const auto& ref3 = body3_ref[i];
            if (ref2.time > run_until + 1.0e-14) {
                break;
            }
            while (time < ref2.time - 1.0e-14) {
                const double h = std::min(dt, ref2.time - time);
                last_contact = EvaluateContact(pin_graph, bore_sdf, state, contact);
                if (std::isnan(first_contact_time) && last_contact.active_samples > 0) {
                    first_contact_time = time;
                }
                max_effective_penetration_seen =
                    std::max(max_effective_penetration_seen, last_contact.max_effective_penetration);
                max_patch_count = std::max(max_patch_count, last_contact.patch_count);

                const ChVector3d gravity_force(0, -9.80665 * mass, 0);
                const ChVector3d total_force = gravity_force + last_contact.force;
                last_acc_com = total_force / mass;

                const Mat3 rmat = ToMat3(state.rot);
                const ChVector3d torque_body = Transpose(rmat) * last_contact.torque;
                const ChVector3d angular_momentum = inertia_body * state.omega_body;
                last_alpha_body =
                    inertia_inv_body * (torque_body - state.omega_body.Cross(angular_momentum));

                state.vel += last_acc_com * h;
                state.pos += state.vel * h;
                state.omega_body += last_alpha_body * h;
                const Quat omega_quat{0.0, state.omega_body.x(), state.omega_body.y(), state.omega_body.z()};
                const Quat qdot = Multiply(state.rot, omega_quat);
                state.rot.w += 0.5 * qdot.w * h;
                state.rot.x += 0.5 * qdot.x * h;
                state.rot.y += 0.5 * qdot.y * h;
                state.rot.z += 0.5 * qdot.z * h;
                Normalize(state.rot);
                time += h;
            }

            BodyKinematics b2 = KinematicsAt(state, r2_local, last_acc_com, last_alpha_body);
            BodyKinematics b3 = KinematicsAt(state, r3_local, last_acc_com, last_alpha_body);
            AddComponentErrors(b2.pos, ref2.pos, b2_x_err, b2_y_err, b2_z_err);
            AddComponentErrors(b3.pos, ref3.pos, b3_x_err, b3_y_err, b3_z_err);
            if (ref2.time >= 0.05) {
                b2_y_err_after.push_back(b2.pos.y() - ref2.pos.y());
                b2_z_err_after.push_back(b2.pos.z() - ref2.pos.z());
                b3_y_err_after.push_back(b3.pos.y() - ref3.pos.y());
                b3_z_err_after.push_back(b3.pos.z() - ref3.pos.z());
            }
            max_body3_xy_radius = std::max(max_body3_xy_radius, std::sqrt(b3.pos.x() * b3.pos.x() +
                                                                           b3.pos.y() * b3.pos.y()));

            frames << ref2.time << ","
                   << b2.pos.x() << "," << b2.pos.y() << "," << b2.pos.z() << ","
                   << ref2.pos.x() << "," << ref2.pos.y() << "," << ref2.pos.z() << ","
                   << b3.pos.x() << "," << b3.pos.y() << "," << b3.pos.z() << ","
                   << ref3.pos.x() << "," << ref3.pos.y() << "," << ref3.pos.z() << ","
                   << b2.vel.x() << "," << b2.vel.y() << "," << b2.vel.z() << ","
                   << ref2.vel.x() << "," << ref2.vel.y() << "," << ref2.vel.z() << ","
                   << b3.vel.x() << "," << b3.vel.y() << "," << b3.vel.z() << ","
                   << ref3.vel.x() << "," << ref3.vel.y() << "," << ref3.vel.z() << ","
                   << last_contact.patch_count << "," << last_contact.active_samples << ","
                   << last_contact.min_phi << "," << last_contact.max_effective_penetration << ","
                   << last_contact.force.x() << "," << last_contact.force.y() << "," << last_contact.force.z() << ","
                   << last_contact.torque.x() << "," << last_contact.torque.y() << "," << last_contact.torque.z()
                   << "\n";
        }
        const auto integration_end = Clock::now();

        std::ofstream summary(out_dir / "summary.csv");
        summary << "quantity,value\n";
        summary << "duration," << run_until << "\n";
        summary << "dt," << dt << "\n";
        summary << "voxel_size," << voxel_size << "\n";
        summary << "pressure_at_bpen," << pressure_at_bpen << "\n";
        summary << "damping_pressure," << damping_pressure << "\n";
        summary << "bore_vertices," << bore_mesh.vertices.size() << "\n";
        summary << "pin_vertices," << pin_mesh_body3.vertices.size() << "\n";
        summary << "compound_mass," << mass << "\n";
        summary << "compound_cm_x," << compound_cm_local.x() << "\n";
        summary << "compound_cm_y," << compound_cm_local.y() << "\n";
        summary << "compound_cm_z," << compound_cm_local.z() << "\n";
        summary << "first_contact_time," << first_contact_time << "\n";
        summary << "reference_first_clearance_time,0.045253\n";
        summary << "max_body3_xy_radius," << max_body3_xy_radius << "\n";
        summary << "reference_max_body3_xy_radius,0.04426075\n";
        summary << "max_effective_penetration_seen," << max_effective_penetration_seen << "\n";
        summary << "max_patch_count," << max_patch_count << "\n";
        summary << "body2_y_rms_error," << Rms(b2_y_err) << "\n";
        summary << "body2_z_rms_error," << Rms(b2_z_err) << "\n";
        summary << "body3_y_rms_error," << Rms(b3_y_err) << "\n";
        summary << "body3_z_rms_error," << Rms(b3_z_err) << "\n";
        summary << "body2_y_max_abs_error," << MaxAbs(b2_y_err) << "\n";
        summary << "body2_z_max_abs_error," << MaxAbs(b2_z_err) << "\n";
        summary << "body3_y_max_abs_error," << MaxAbs(b3_y_err) << "\n";
        summary << "body3_z_max_abs_error," << MaxAbs(b3_z_err) << "\n";
        summary << "body2_y_rms_error_t_ge_0p05," << Rms(b2_y_err_after) << "\n";
        summary << "body2_z_rms_error_t_ge_0p05," << Rms(b2_z_err_after) << "\n";
        summary << "body3_y_rms_error_t_ge_0p05," << Rms(b3_y_err_after) << "\n";
        summary << "body3_z_rms_error_t_ge_0p05," << Rms(b3_z_err_after) << "\n";
        summary << "integration_wall_time_seconds,"
                << std::chrono::duration<double>(integration_end - integration_start).count() << "\n";
        summary << "wall_time_seconds_before_summary,"
                << std::chrono::duration<double>(integration_end - wall_start).count() << "\n";

        std::cout << "Wrote " << (out_dir / "rev_joint_clearance_frames.csv").string() << std::endl;
        std::cout << "Wrote " << (out_dir / "summary.csv").string() << std::endl;
        std::cout << "first_contact_time=" << first_contact_time
                  << " max_body3_xy_radius=" << max_body3_xy_radius
                  << " body3_y_rms=" << Rms(b3_y_err) << std::endl;
        return 0;
    } catch (const std::exception& e) {
        std::cerr << "ERROR: " << e.what() << std::endl;
        return 2;
    }
}
